package ar.com.agroasistencia.vistas.principal;

import com.sun.awt.AWTUtilities;
import com.sun.istack.internal.logging.Logger;
import java.util.logging.Level;

/**
 *
 * @author LucasGoicoechea@gmail.com
 * @version 1.1
 * @since 2018-Diciembre
 * @description Esta clase pertenece a la GUI y es la encargada de generar un cartel de presentación al iniciar el software
 */
public class SplashFrame extends javax.swing.JFrame implements Runnable {

    private Thread tiempo= null;
    /**
     * Metodo de arranque del Software
     * Se muestra cartel y luego se quita
     */
    public SplashFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this, false);
        tiempo = new Thread(this);
        tiempo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSplash = new javax.swing.JPanel();
        jLCartelSoft = new javax.swing.JLabel();
        jLCartelAutor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLCartelSoft.setBackground(new java.awt.Color(255, 102, 51));
        jLCartelSoft.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLCartelSoft.setText("SOFTWARE DE ASISTENCIA AL AGRO");

        jLCartelAutor.setBackground(new java.awt.Color(0, 204, 204));
        jLCartelAutor.setForeground(new java.awt.Color(51, 0, 51));
        jLCartelAutor.setText("Autor: LucasGoicoEchea@gmail.com");

        javax.swing.GroupLayout jPanelSplashLayout = new javax.swing.GroupLayout(jPanelSplash);
        jPanelSplash.setLayout(jPanelSplashLayout);
        jPanelSplashLayout.setHorizontalGroup(
            jPanelSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSplashLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLCartelAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSplashLayout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addComponent(jLCartelSoft, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanelSplashLayout.setVerticalGroup(
            jPanelSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSplashLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLCartelSoft, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLCartelAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSplash, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelSplash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
       /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLCartelAutor;
    private javax.swing.JLabel jLCartelSoft;
    private javax.swing.JPanel jPanelSplash;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(tiempo != null){
            try{
                Thread.sleep(2000);
                this.dispose();
                LoginFrame.main(null);
                Thread.sleep(4000);
            }
            catch (InterruptedException ex) {
                 Logger.getLogger(SplashFrame.class).log(Level.SEVERE,"El software no pudo inicializar por el siguiente error:", ex );
            }
            tiempo = null;
        }    
    }
}
