package ar.com.agroasistencia.modelo.modeloHibernate;
// Generated 14/12/2018 07:18:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AgroCampos generated by hbm2java
 */
public class AgroCampos  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Integer superficie;
     private String usuarioAlta;
     private Set loteses = new HashSet(0);

    public AgroCampos() {
    }

    public AgroCampos(String nombre, Integer superficie, String usuarioAlta, Set loteses) {
       this.nombre = nombre;
       this.superficie = superficie;
       this.usuarioAlta = usuarioAlta;
       this.loteses = loteses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getSuperficie() {
        return this.superficie;
    }
    
    public void setSuperficie(Integer superficie) {
        this.superficie = superficie;
    }
    public String getUsuarioAlta() {
        return this.usuarioAlta;
    }
    
    public void setUsuarioAlta(String usuarioAlta) {
        this.usuarioAlta = usuarioAlta;
    }
    public Set getLoteses() {
        return this.loteses;
    }
    
    public void setLoteses(Set loteses) {
        this.loteses = loteses;
    }




}


